#%RAML 1.0
title: Api node framework specifications
baseUri: /{version}
version: v1
protocols:
    - HTTP
    - HTTPS

#uses:
#    TypeUser: types/user.raml

/camera:
    description: Device ressource, base path to command and info devices

    /info:
        get:
            description: Get full description of devices
            responses:
                200:
                    body:
                        application/json:
                            type: object
                            properties:
                                id: number
                                command: boolean
                                group: number
                                updated_at: datetime
                            example: |
                                {
                                  "id": 0,
                                  "command": true,
                                  "group": 0,
                                  "updated_at": "2017-03-01T10:10:10Z"
                                }

    /snapshot:
        get:
            description: Controll a device - send signal to a device
            queryParameters:
                camera:
                    description: Group of the chacon device
                    type: string
                    example: "video_id_1"
            responses:
                200:
                    body:
                        application/json:
                            type: object
                            properties:
                                url: string
                                filename: string
                                created_at: datetime
                            example: |
                                {
                                  "url": "http://localhost:3001/service-data/cameraA/456875421321.jpg"
                                  "filename": "456875421321.jpg",
                                  "created_at": "2017-03-01T10:10:10Z"
                                }
