#%RAML 1.0
title: Api node framework specifications
baseUri: /{version}
version: v1
protocols:
    - HTTP
    - HTTPS

#uses:
#    TypeUser: types/user.raml

/voices:
    description: Device ressource, base path to command and info devices
    /say:
        get:
            description: Get full description of devices
            queryParameters:
                voice:
                    description: Name (id) selected voice to say message
                    type: string
                    example: "voice_id_1"
                message:
                    description: Message to say
                    type: string
                    example: "Hello every body"
            responses:
                200:
                    body:
                        application/json:
                            type: object
                            properties:
                                voice: string
                                said: boolean
                            example: |
                                {
                                  "voice": "voice_id_1",
                                  "said": true
                                }
    /info:
        get:
            description: Get full description of devices
            responses:
                200:
                    body:
                        application/json:
                            type: object
                            properties:
                                id: number
                                command: boolean
                                group: number
                                group1: object
                                updated_at: datetime
                            example: |
                                {
                                  "id": 0,
                                  "command": true,
                                  "group": 0,
                                  "updated_at": "2017-03-01T10:10:10Z",
                                  "group1": {}
                                }
